"""Add auto_trade_enabled to users table

Revision ID: 1e2f38bf9665
Revises: 70f09a16821c
Create Date: 2025-06-12 07:30:12.168934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2f38bf9665'
down_revision: Union[str, None] = '70f09a16821c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
