"""Add payment_invoices table

Revision ID: 237d42842d27
Revises: d7f65be6c812
Create Date: 2025-06-16 02:56:42.145379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237d42842d27'
down_revision: Union[str, None] = 'd7f65be6c812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('ipaymu_trx_id', sa.Integer(), nullable=True),
    sa.Column('payment_url', sa.String(), nullable=False),
    sa.Column('package_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_invoices_reference_id'), ['reference_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_invoices_user_telegram_id'), ['user_telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_invoices_user_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_payment_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_payment_invoices_reference_id'))
        batch_op.drop_index(batch_op.f('ix_payment_invoices_id'))

    op.drop_table('payment_invoices')
    # ### end Alembic commands ###
