"""Refactor signal table with unique_id and timestamps

Revision ID: 5e43462de85f
Revises: 479f834fac60
Create Date: 2025-06-11 15:04:14.006836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e43462de85f'
down_revision: Union[str, None] = '479f834fac60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
