"""Add trading_style to signals table

Revision ID: a8474eb06424
Revises: 5e43462de85f
Create Date: 2025-06-11 15:12:58.544995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8474eb06424'
down_revision: Union[str, None] = '5e43462de85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_style', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_signals_trading_style'), ['trading_style'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_trading_style'))
        batch_op.drop_column('trading_style')

    # ### end Alembic commands ###
