"""Add prefix and suffix to users table

Revision ID: d7f65be6c812
Revises: 1e2f38bf9665
Create Date: 2025-06-15 22:51:25.946091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f65be6c812'
down_revision: Union[str, None] = '1e2f38bf9665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol_prefix', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('symbol_suffix', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('symbol_suffix')
        batch_op.drop_column('symbol_prefix')

    # ### end Alembic commands ###
